pipeline:
  name: remote-test
  identifier: remotetest
  projectIdentifier: shauryatesting
  orgIdentifier: default
  tags: {}
  properties:
    ci:
      codebase:
        connectorRef: account.sahithiTf6
        build: <+input>
        depth: <+input>
        sslVerify: <+input>
        prCloneStrategy: MergeCommit
  stages:
    - stage:
        name: test
        identifier: test
        description: ""
        type: CI
        spec:
          cloneCodebase: true
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
          execution:
            steps:
              - step:
                  type: Run
                  name: Run_1
                  identifier: Run_1
                  spec:
                    shell: Sh
                    command: echo hw
